@baseUrl = http://127.0.0.1:8027/beta
@apikey = xxx

### add server
POST {{baseUrl}}/add-server
Content-Type: application/json
Authorization: Bearer {{apikey}}

{
  "name": "hf-mcp",
  "author_name": "huggingface",
  "title": "HuggingFace MCP Server",
  "description": "HuggingFace official MCP server.",
  "server_key": "hf-mcp",
  "server_url": "https://huggingface.co/mcp",
  "config_name": "hf-mcp"
}

### get servers
POST {{baseUrl}}/get-servers
Content-Type: application/json
Authorization: Bearer {{apikey}}

{
  "page": 1,
  "limit": 10
}

### get server
POST {{baseUrl}}/get-server
Content-Type: application/json
Authorization: Bearer {{apikey}}

{
  "name": "time-mcp",
  "author_name": "anthropic"
}

### save user
POST {{baseUrl}}/save-user
Content-Type: application/json
Authorization: Bearer {{apikey}}

{
  "email": "test@test.com1",
  "nickname": "test",
  "avatar_url": "https://test.com/avatar.png",
  "signin_type": "email",
  "signin_provider": "google",
  "signin_openid": "1234567890",
  "signin_ip": "127.0.0.1"
}

### get user
POST {{baseUrl}}/get-user
Content-Type: application/json
Authorization: Bearer {{apikey}}

{
  "email": "test@test.com"
} 